export const enum AppColors {
  YELLOW = '#ffcc00',
  YELLOW_LIGHT = '#ffe417',
  YELLOW_LIGHTER = '#ffff17',
  YELLOW_DARK = '#e0ad15',
  YELLOW_DARKER = '#bc9112',
  GREEN = '#42b883',
  GREEN_LIGHT = '#42d392',
  GREEN_LIGHTER = '#35eb9a',
  GREEN_DARK = '#33a06f',
  GREEN_DARKER = '#155f3e',
  BLUE = '#3b8eed',
  BLUE_LIGHT = '#549ced',
  BLUE_LIGHTER = '#00cae0',
  BLUE_DARK = '#647eff',
  BLUE_DARKER = '#3468a3',
  PURPLE = '#de41e0',
  PURPLE_LIGHT = '#e936eb',
  PURPLE_LIGHTER = '#f616f8',
  PURPLE_DARK = '#823c83',
  PURPLE_DARKER = '#602960',
  TRANSPARENT = 'transparent'
}

export const enum AppColorsText {
  YELLOW = 'yellow',
  YELLOW_LIGHT = 'yellow-light',
  YELLOW_LIGHTER = 'yellow-lighter',
  YELLOW_DARK = 'yellow-dark',
  YELLOW_DARKER = 'yellow-darker',
  GREEN = 'green',
  GREEN_LIGHT = 'green-light',
  GREEN_LIGHTER = 'green-lighter',
  GREEN_DARK = 'green-dark',
  GREEN_DARKER = 'green-darker',
  BLUE = 'blue',
  BLUE_LIGHT = 'blue-light',
  BLUE_LIGHTER = 'blue-lighter',
  BLUE_DARK = 'blue-dark',
  BLUE_DARKER = 'blue-darker',
  PURPLE = 'purple',
  PURPLE_LIGHT = 'purple-light',
  PURPLE_LIGHTER = 'purple-lighter',
  PURPLE_DARK = 'purple-dark',
  PURPLE_DARKER = 'purple-darker',
  TRANSPARENT = 'transparent'
}
