name: Test, Lint, Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Получить код
        uses: actions/checkout@v3
      - name: Кэшировать зависимости
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Установить зависимости
        run: |
          cd client
          npm ci
      - name: Исправление кода приложения
        run: |
          cd client
          npm run lint
  deploy:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Получить код
        uses: actions/checkout@v3
      - name: Кэшировать зависимости
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Установить зависимости
        run: |
          cd client
          npm ci
      - name: Билд продакшн версии приложения
        run: |
          cd client
          npm run predeploy
      - name: Деплой в ветку gh-pages
        run: |
          cd client
          npm run deploy